# Generated by Django 4.1.13 on 2024-05-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_expense_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
    ]
