# Generated by Django 4.1.13 on 2024-05-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_expense_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='username',
            new_name='payee',
        ),
    ]
